#pragma once

#define HELMET_PIN_I2C_SDA 8
#define HELMET_PIN_I2C_SCL 9
#define HELMET_PIN_DS18B20 4
#define HELMET_PIN_SOS 5
#define HELMET_PIN_LED_GREEN 6
#define HELMET_PIN_LED_YELLOW 7
#define HELMET_PIN_LED_RED 15
#define HELMET_PIN_BUZZER 16
#define HELMET_PIN_VIBRATION 17
#define HELMET_PIN_BATTERY_ADC 1

#define HELMET_TEMPERATURE_WARNING_C 50.0f
#define HELMET_TEMPERATURE_CRITICAL_C 60.0f
#define HELMET_CO_WARNING_PPM 50.0f
#define HELMET_CO_CRITICAL_PPM 100.0f
#define HELMET_LOW_BATTERY_PERCENT 20.0f

#define HELMET_SCHEMA_VERSION "1.0"
#define HELMET_SOURCE_HARDWARE "HARDWARE"
