import { RiskBadge } from '../components/Badges'
import type { DeviceState } from '../types/dashboard'

const yesNo = (value: boolean | undefined) => value ? 'ON' : 'OFF'

export function DeviceDetailPage({ device, back }: { device?: DeviceState; back: () => void }) {
  if (!device) return <section><button className="text-button" onClick={back}>Back to devices</button><p className="empty-state">Device not found in current runtime state.</p></section>
  const telemetry = device.latest_telemetry; const health = device.latest_health; const actuators = device.actuators
  return <section><button className="text-button" onClick={back}>← Devices</button><div className="detail-heading"><div><p className="eyebrow">DEVICE DETAIL</p><h2>{device.device_id}</h2></div><div><span className={`status-pill status-${device.device_status.toLowerCase()}`}>{device.device_status}</span> <RiskBadge level={device.risk_level} /></div></div><p className="last-update">Latest timestamp: {device.last_seen ? new Date(device.last_seen).toLocaleString() : 'Unavailable'}</p><div className="detail-grid"><section><h3>Telemetry</h3><dl className="detail-list"><div><dt>Temperature</dt><dd>{telemetry?.temperature ?? 'Unavailable'} °C</dd></div><div><dt>CO</dt><dd>{telemetry?.co ?? 'Unavailable'}</dd></div><div><dt>Movement</dt><dd>{device.movement}</dd></div><div><dt>Fall</dt><dd>{telemetry?.fall ? 'Yes' : 'No'}</dd></div><div><dt>Immobile</dt><dd>{telemetry?.immobile ? 'Yes' : 'No'}</dd></div><div><dt>SOS</dt><dd>{telemetry?.sos ? 'Yes' : 'No'}</dd></div></dl></section><section><h3>Device health</h3><dl className="detail-list"><div><dt>Battery</dt><dd>{health?.battery ?? telemetry?.battery ?? 'Unavailable'}%</dd></div><div><dt>Wi-Fi</dt><dd>{health?.wifi ?? telemetry?.wifi ?? 'Unavailable'}</dd></div><div><dt>MQTT</dt><dd>{health?.mqtt ?? telemetry?.mqtt ?? 'Unavailable'}</dd></div><div><dt>Uptime</dt><dd>{health?.uptime_seconds ?? 'Unavailable'} seconds</dd></div></dl></section><section><h3>Sensor health</h3><dl className="detail-list"><div><dt>Temperature Sensor</dt><dd>{health?.temperature_sensor ?? 'Unavailable'}</dd></div><div><dt>CO Sensor</dt><dd>{health?.co_sensor ?? 'Unavailable'}</dd></div><div><dt>IMU Sensor</dt><dd>{health?.imu_sensor ?? 'Unavailable'}</dd></div></dl></section><section><h3>LOCAL ACTUATORS</h3><dl className="detail-list"><div><dt>LED</dt><dd>{actuators?.led ?? 'Unavailable'}</dd></div><div><dt>Buzzer</dt><dd>{actuators ? yesNo(actuators.buzzer) : 'Unavailable'}</dd></div><div><dt>Vibration</dt><dd>{actuators ? yesNo(actuators.vibration) : 'Unavailable'}</dd></div></dl></section><section><h3>IMU</h3><dl className="detail-list imu-list">{(['ax', 'ay', 'az', 'gx', 'gy', 'gz'] as const).map((axis) => <div key={axis}><dt>{axis}</dt><dd>{telemetry?.[axis] ?? 'Unavailable'}</dd></div>)}</dl></section></div></section>
}
